### ISSUE TITLE
CAS: invalid content-type for jasig 4.1 answer

### ISSUE THREAD

**Issue by dgeo** [netmagis/netmagis#153]
Hi,

Trying here to use netmagis with CAS auth: my cas server's response (jasig 4.1) replies with 'application/xml' Content-Type, and 'login' tcl script seems to only accept text/html (L.194) (the response in CASv2 can only be XML AFAIK !?)

I've an 'Invalid CAS answer' from line 226.

If I replace text/html by application/xml on line 194 (that's not a solution, just a test…), it works !

**Comment by pdav** [comment]
Thanks for this report. The MIME type of CAS answer is specific to the configuration of the CAS server.
However, Netmagis should handle various configurations.
Your workaround is perfect for the moment.

**Comment by pdav** [comment]
Apparently, from the CAS v3 protocol specifications, our code seem to be compatible with CAS v3. We have to test with jasig 4.1 in order to check the content-type of answer.

Could you provide us with your "casurl" parameter?

**Comment by dgeo** [comment]
I'ts not publicly available (and is only 4.0 for now). However I'm pretty sure that it has to be application/xml at least since CAS 2.
Here we use jasig cas with either nginx and apache frontend.
Another improvement that may be nice would be to only use cas with attributes (needs some mapping with internal names as LDAP), eliminating LDAP dependency in our case...

I may provide a test CAS server (privately), but not very quickly ...

**Comment by dgeo** [comment]
Sorry, smartphone misuse here :/

**Comment by pdav** [comment]
About the "casurl" parameter: just provide the path-name. iIs it "/cas" or something else?

**Comment by dgeo** [comment]
Le 20 décembre 2015 09:56:03 GMT+01:00, Pierre DAVID <notifications@github.com> a écrit :
>About the "casurl" parameter: just provide the path-name. iIs it "/cas"
>or something else?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pdav/netmagis/issues/153#issuecomment-166087126

Sorry... Yes it's /cas  for cas  v1&v2, /cas/p3 for v3.
-- 
geoffroy desvernay

**Comment by pdav** [comment]
Which one do you use with Netmagis?

**Comment by dgeo** [comment]
Le 21 décembre 2015 10:01:48 GMT+01:00, Pierre DAVID <notifications@github.com> a écrit :
>Which one do you use with Netmagis?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pdav/netmagis/issues/153#issuecomment-166240921

Tried both... (V3 giving /cas/p3 instead of /cas) Same problem. Currently using v2.
-- 
geoffroy desvernay

**Comment by dgeo** [comment]
As of https://apereo.github.io/cas/4.2.x/protocol/CAS-Protocol-Specification.html , cas official specs does not seems to dictate the mime-type of the response… Which is XML, I think application/xml IS the right content-type, ans text/html MAY be accepted (parsed as XML).
In any cas I don't see any case where no accepting the right content-type would hurt :)

I'm not tcl-skilled at all, woule a simple ```  text/html|application/xml)``` work here ?
I may do e PR if it can help, but I don't kile duplicating code :)

**Comment by dgeo** [comment]
And happy new year !

**Comment by dgeo** [comment]
Thank you !!!
