### ISSUE TITLE
search wildcard *

### ISSUE THREAD

**Issue by Bahram123** [netmagis/netmagis#169]
Hello

I've modify the search fonction for able searching with the charactere * wildcard
Enter at least the char
: for the @MAC 
. for  @IP

example

00:* for wildcard searching @Mac
192.168.*  for wildcard searching @IP
tot*: for wildcard searching host 
file is /usr/lib/cgi-bin/netmagis/search

Regards,
[search.zip](https://github.com/pdav/netmagis/files/840710/search.zip)

**Comment by fmeynadier** [comment]
Hello,

This would be an interesting feature, and it does not seem it finally made it to v2.3.4…
Would it be of any help if I transform the patch proposed by  @Bahram123 into a pull request ?

**Comment by pdav** [comment]
Thanks!
